{"uuid": "18d07c0b-d21c-4095-921b-f137a8a0f3cc", "counter": 20, "stdout": "\u001b[0;31mfatal: [localhost]: FAILED! => {\"changed\": false, \"msg\": \"Failed connection: URLError: code: 403 reason: Invalid Credential\"}\u001b[0m", "start_line": 17, "end_line": 18, "runner_ident": "bd1e6293-dd11-4738-b953-8bcdc635bbfe", "event": "runner_on_failed", "pid": 23, "created": "2022-10-22T21:37:07.530266", "parent_uuid": "76109d32-7bea-7dc8-6989-000000000036", "event_data": {"playbook": "1.1_palo_facts.yml", "playbook_uuid": "44f28fea-01bc-4177-8a53-ec1a6f4bfcff", "play": "localhost", "play_uuid": "76109d32-7bea-7dc8-6989-000000000005", "play_pattern": "localhost", "task": "Get vr info", "task_uuid": "76109d32-7bea-7dc8-6989-000000000036", "task_action": "paloaltonetworks.panos.panos_virtual_router_facts", "resolved_action": "paloaltonetworks.panos.panos_virtual_router_facts", "task_args": "", "task_path": "/runner/project/roles/palo_facts/tasks/palo_vr_facts.yml:1", "role": "palo_facts", "host": "localhost", "remote_addr": "127.0.0.1", "res": {"msg": "Failed connection: URLError: code: 403 reason: Invalid Credential", "invocation": {"module_args": {"provider": {"username": "ansible_automation", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "ip_address": "10.0.0.102", "port": 443, "api_key": null, "serial_number": null}, "name": "default", "username": "admin", "port": 443, "ip_address": null, "password": null, "api_key": null, "template": null, "template_stack": null}}, "deprecations": [{"msg": "Deprecated; use panos_virtual_router with state=gathered", "version": "3.0.0", "collection_name": "paloaltonetworks.panos"}], "_ansible_no_log": false, "changed": false}, "start": "2022-10-22T21:37:05.203712", "end": "2022-10-22T21:37:07.530067", "duration": 2.326355, "ignore_errors": null, "event_loop": null, "uuid": "18d07c0b-d21c-4095-921b-f137a8a0f3cc"}}